<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
<title>Hao's de Vietnamese restaurant</title>
<h1>The Vietnamese Restaurant</h1>
<details>
     <summary>In Vietnam, before eating we say “Chúc ngon miệng!”-- meaning 'enjoy your meal' (but of course you will.)
While Vietnamese cuisine abroad still flies under the banners of phở and bánh mì, the full spectrum of Vietnamese food is a symphony of delightfully textured, bright and piquant flavours.
The Vietnamese love their food and cooks make the most of each region's abundance produce and special ingredients to make their meals. Northern food is known for its simplicity; the dishes of central Vietnam are generous in spice and quantity; Southerners like to add sugar. Wherever you travel across the country, you're sure to eat well.</summary>
<p>This is the Vietnamese Restaurant and we provide our traditional foods. You can chance to taste all the flavours from Vietnam Cuisine, which is known as one of the top delicious countries in the world.</p></details>
</head>
<body>  
    <main>
    <h2><em>MENU</em></h2>
<div>
    <ol>
        <li>Vietnamese Food</li>
        <li>Snacks</li>
        <li>Brunch</li>
    </ol>
</div>
<section>
    <h3> TOP BEST OF THE BEST</h3>
    <ul>
    <li><figure><img src="https://vietnamnomad.com/wp-content/uploads/2022/07/Banh-Xeo-A-guide-to-Vietnamese-Pancakes-Vietnamnomad.jpg" alt="Vietnamese pancakes" width="50%" class="thumbnail"/><figcaption>Vietnamese Pancakes</figcaption></figure></li>
    <li><figure><img src="https://luhanhvietnam.com.vn/du-lich/vnt_upload/news/09_2022/quan-com-tam-o-ha-noi-.jpg" alt="Broken rice with ribs grilled" width="50%" class="thumbnail"/><figcaption>Broken Rice with Grilled Ribs</figcaption></figure></li>
    <li><figure><img src="https://i0.wp.com/eatfoodlicious.com/wp-content/uploads/2021/05/frame-000053.jpg?fit=3840%2C2160&ssl=1" width="50%" alt="Vietnamese rice noodle with beef slices" class="thumbnail"/><figcaption>Phở-Rice noodle with beef slices</figcaption></figure></li>
    </ul>
</section>
    <div>
        <fieldset>
            <legend>Do you want to share bills?</legend>
            <label><input id="share" type="radio" name="sharebills" value="share" checked> Share</label>
            <label><input id="noshare" type="radio" name="sharebills" value="noshare"> Noshare</label>
          </fieldset>
    </div>
</main>
</body>
<footer>
    <a href="https://www.tripadvisor.com/Restaurants-g293925-c41-Ho_Chi_Minh_City.html">If you don't see our restaurant, please check this link</a>
    <hr>
    <p>2023 by Nguyen Hao</p>
</footer>
</html>
